config/routes.rb
OralExamRails::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :scenarios, :sections

  root 'static_pages#landing'
  match '/home',         to: 'scenarios#index',         via: 'get'
  match '/admin_page',   to: 'admin/dashboard#index',   via: 'get'  
  get "sections/new"
  get "scenarios/new"
  get "static_pages/home"
  get "static_pages/history"
  get "static_pages/physical"  
  get "static_pages/lab"  
  get "static_pages/scc"  
  get "static_pages/bcc"  
  get "static_pages/melanoma"  
  get "static_pages/cystic"  
  get "static_pages/thyroid"  
  get "static_pages/lymphona"  
  get "static_pages/radiation"  
  get "static_pages/landing"

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/inquest.rb
class Inquest < ActiveRecord::Base
	belongs_to :section
	belongs_to :scenario
end

app/models/scenario.rb
class Scenario < ActiveRecord::Base
end

app/models/section.rb
class Section < ActiveRecord::Base
	belongs_to :scenario
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/inquests_controller.rb
class InquestsController < ApplicationController
  def new
  end
end

app/controllers/scenarios_controller.rb
class ScenariosController < ApplicationController

  def show
    @scenario = Scenario.find(params[:id])
    @nav_sections = Section.where(scenario: params[:id])
  end

  def index
    @scenarios = Scenario.all
  end

  def new
  end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  def new
  end

  # Nav sections is a list of sections in the same scenario for the nav menu.

  def show
    @section = Section.find(params[:id])  	
    @nav_sections = Section.where(scenario_id: @section.scenario_id).order(:order)
    @inquests = Inquest.where(section_id: params[:id]).order(:order)
    @scenario = Scenario.where(id: @section.scenario_id)[0]
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inquests_helper.rb
module InquestsHelper
end

app/helpers/scenarios_helper.rb
module ScenariosHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/inquests/new.html.erb
<h1>Inquests#new</h1>
<p>Find me in app/views/inquests/new.html.erb</p>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
    <div class='navbar-header'>
        <span class='navbar-brand'><%= link_to "Oral Exam App", home_path %>
        </span>

    </div>
    <ul class="nav navbar-nav">    
        <li class="active"><%= link_to "Admin", admin_page_path %>
        </li>
    </ul>
</nav>
<% if controller_name == 'static_pages' && action_name == 'landing' %>
	<div id='landing_img'>
		<div id='landing_blurb'>
			<h1>Master the General Surgery Certifying Examination</h1>
			<h2>Practice with online case studies written by surgeons</h2>
			<div id='start_link'>
				<ul class="nav nav-pills">
				    <li class='active'><%= link_to "Use it now", home_path%></li>
				</ul>
			</div>
		</div>
	</div>
<% else %>
	<div id='logo'>
	    <h1>Oral Exam App</h1>
	</div>
<% end %>

app/views/layouts/_patient_header.html.erb
<h2 style='text-align: center'>Patient #1.</h2>

<div class='dropdown'>
    <a role='button' id='dLabel' class='btn btn-primary' id='dropdownMenu1' data-toggle='dropdown'>Navigation <span class='caret'></span></a>
	<ul class='dropdown-menu' role='menu' aria-labelledby="dropdownMenu1" ng-init = "
	    links = [
	        {
	            title: 'History',
	            loc: 'history.html',
	            indent: '1'
	        },
	        {
	            title: 'Physical',
	            loc: 'physical.html',
	            indent: '1'

	        },
	        {
	            title: 'Lab',
	            loc: 'lab.html',
	            indent: '1'
	        },
	        {
	            title: 'Squamous Cell Carcinoma',
	            loc: 'scc.html',
	            indent: '2'
	        },
	        {
	            title: 'Radiation Treatment',
	            loc: 'radiation.html',
	            indent: '3'
	        },	        
	        {
	            title: 'Basal Cell Carcinoma',
	            loc: 'bcc.html',
	            indent: '2'
	        },
	        {
	            title: 'Melanoma',
	            loc: 'melanoma.html',
	            indent: '2'
	        }, 
	        {
	            title: 'Cystic',
	            loc: 'cystic.html',
	            indent: '2'
	        }, 
	        {
	            title: 'Thyroid',
	            loc: 'thyroid.html',
	            indent: '2'
	        },
	        {
	            title: 'Lymphona',
	            loc: 'lymphona.html',
	            indent: '2'
	        }

	    ]
	">
	    <li role='presentation' ng-repeat='link in links' ng-class='"indent" + link.indent'> <a role ='menuitem' tabindex='2' href='{{link.loc}}'>{{link.title}}</a></li>
	</ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app>
  <head>
    <%= favicon_link_tag 'favicon.ico' %>  
    <title>Oral Exam App | <%= yield(:subtitle) %></title>
      <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
      <%= javascript_include_tag "application", "angular" => true %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

  </head>
  <body>
     <%= render 'layouts/header' %>
     <div class='container'>
       <%= yield %>
     </div>
  </body>
</html>

app/views/scenarios/index.html.erb
<% provide(:title, 'Scenarios') %>
<h1>Scenarios</h1>

<ul class="scenarios">
  <% @scenarios.each do |scenario| %>
    <li>
      <%= link_to "Patient # #{scenario.id} #{scenario.name}", Section.where(scenario_id: scenario.id).order(:order).first() %>
    </li>
  <% end %>
</ul>

app/views/scenarios/new.html.erb
<h1>Scenarios#new</h1>
<p>Find me in app/views/scenarios/new.html.erb</p>

app/views/scenarios/show.html.erb
<h1><%= @scenario.name %></h1>

<div class='dropdown'>
    <a role='button' id='dLabel' class='btn btn-primary' id='dropdownMenu1' data-toggle='dropdown'>Navigation <span class='caret'></span></a>
	<ul class='dropdown-menu' role='menu' aria-labelledby="dropdownMenu1">
	    <% @nav_sections.each do |section| %>
	        <li role='presentation'> <span role ='menuitem' tabindex='2'><%= link_to section.name, section %>
    </li></span></li>
	    <% end %>
	</ul>
</div>

app/views/sections/new.html.erb
<h1>Sections#new</h1>
<p>Find me in app/views/sections/new.html.erb</p>

app/views/sections/show.html.erb
<h3>Patient #<%= @scenario.id %> <%= @scenario.name %></h3>

<div class='dropdown'>
    <a role='button' id='dLabel' class='btn btn-primary' id='dropdownMenu1' data-toggle='dropdown'>Navigation <span class='caret'></span></a>
	<ul class='dropdown-menu' role='menu' aria-labelledby="dropdownMenu1">
	    <% @nav_sections.each do |section| %>
	        <li role='presentation'> <span role ='menuitem' class='menu_link indent<%= section.depth %>'><%= link_to section.name, section %></span></li>
	    <% end %>
	</ul>
</div>

<h2><%= @section.name %></h2>

<%= raw @section.desc %>

<% @inquests.each do |inquest| %>
      <li class='inquest_label' ng-click='inquest<%=inquest.id%>.show = !inquest<%=inquest.id%>.show'><a href=''><%=inquest.label%></a></li>
      <div class='inquest_content' ng-show='inquest<%=inquest.id%>.show'>
          <%= raw inquest.content%>
      </div>
<% end %>

app/views/static_pages/bcc.html.erb
<% provide(:subtitle, 'Basal Cell Carcinoma') %>
<%= render ('layouts/patient_header') %> 

<h2> Basal Cell Carcinoma </h2>

<ul>
  <div>
      <a href=''><li ng-click='action1.show = !action1.show'>Excise with 2mm margins</li></a>
      <p ng-show='action1.show'>Lymph Node Dissection only if clinically positive</p>
  </div>
</ul>    

app/views/static_pages/cystic.html.erb
<% provide(:subtitle, 'Cystic') %>
<%= render ('layouts/patient_header') %> 

<h2> Cystic </h2>

<p> Incomplete page </p>

app/views/static_pages/history.html.erb
<% provide(:subtitle, 'History') %>
<%= render ('layouts/patient_header') %> 
<h2> History </h2>
<h3> Anecdote </h3>
<p> A 56year old male comes to your office when his family physician noted a lump on the side of his neck. </p>
<h3>Ask for details about</h3>
<ul ng-init="questions = [
    {
      caption: 'Onset?',
      desc: 'He first noticed the lump about 2 weeks ago.'
    }, {
      caption: 'Location?',
      desc: 'The lump is placed pretty squarely in the middle of his neck.'
    }, {
      caption: 'Growth?',
      desc: 'He believes that it has grown since the first week he noticed it.'
    }, {
      caption: 'Pain?',
      desc: 'He doesn\'t feel any pain on the lump itself.'
    }, {
      caption: 'Fever?',
      desc: 'He has been running a considerable fever'
    }, {
      caption: 'Chills?',
      desc: 'He has been expieriencing chills off and on.'
    }, {
      caption: 'Recent upper respitory infection/symptoms?',
      desc: 'None that he knows of.'
    }, {
      caption: 'Other lesions or previous surgeries?',
      desc: 'None.'
    }, {
      caption: 'History of malignancy?',
      desc: 'None.'
    }, {
      caption: 'History of smoking, chewing tabacco use or alcohol',
      desc: 'Yes, he is a pack a day smoker and drinks most weekends.'
    }, {
      caption: 'History of radiation?',
      desc: 'None.'
    }, {
      caption: 'Excessive sun exposure?',
      desc: 'He spent a day out in the beach last weekend, but nothing excessive.'
    }, {
      caption: 'Family history of cancers, thyroid disorders, sarcodiosis?',
      desc: 'His mother had lung cancer.'
    }
]">
  <div ng-repeat='question in questions'>
      <a href=''><li ng-click='question.show = !question.show'>{{question.caption}}</li></a>
      <p ng-show='question.show'>{{question.desc}}
  </div>
</ul>

<h3>Next Step</h3>
<a href='physical.html'><button>Physical Exams</button></a>
<br><br><br>

app/views/static_pages/home.html.erb
<p>Try out these example scenarios in order to prepare for your test:
<ul>
<a href='history.html'><li>Patient #1</li></a>
</ul>

app/views/static_pages/lab.html.erb
<% provide(:subtitle, 'Lab') %>
<%= render ('layouts/patient_header') %> 
<h2>Lab</h2>
<ul ng-init="actions =
    [{
        caption: 'Perform FNA',
        desc: 'There are many possible findings from an FNA, and we\'ll explore several of the possibilties.'
    }]">
	<div ng-repeat='action in actions'>
	      <a href=''><li ng-click='action.show = !action.show'>{{action.caption}}</li></a>
	      <div ng-show='action.show'>
	          <p>{{action.desc}}</p>
	          <a href='scc.html'><p><button>Squamous cell Carcinoma</button></a>
	          <a href='bcc.html'><p><button>Basal Cell Carcinoma</button></a>
	          <a href='melanoma.html'><p><button>Melanoma</button></a>
	          <a href='cystic.html'><p><button>Cystic</button></a>
	          <a href='thyroid.html'><p><button>Thyroid</button></a>
	          <a href='lymphona.html'><p><button>Lymphona</button></a>
	      </div>
	  </div>    

</ul>

app/views/static_pages/melanoma.html.erb
<% provide(:subtitle, 'Melanoma') %>
<%= render ('layouts/patient_header') %> 

<h2> Melanoma </h2>

<p> Incomplete page </p>

app/views/static_pages/physical.html.erb
<% provide(:subtitle, 'Physical') %>
<%= render ('layouts/patient_header') %> 
<h2> Physical </h2>
<ul ng-init="actions = [
    {
        caption: 'Perform a full skin exam',
        desc: 'Nothing unusual found.'
    }, {
        caption: 'Perform a bimanual oral exam',
        desc: 'Nothing unusual found.'
    }, {
        caption: 'Papate all lymph node basins',
        desc: 'Nothing unusual found.'
    }
]">
  <div>
      <a href=''><li ng-click='action1.show = !action1.show'>Perform a complete physical exam focusing on the mass.</li></a>
      <p ng-show='action1.show'>the mass is <b>midline</b>, <b>mobile</b>, <b>tender</b>, and <b>not pulsatile</b></p>      
  </div>
  <div ng-repeat='action in actions'>
      <a href=''><li ng-click='action.show = !action.show'>{{action.caption}}</li></a>
      <p ng-show='action.show'>{{action.desc}}</p>
  </div>
</ul>
<h3>Next step</h3>
<a href='lab.html'><button>Lab</button></a>

app/views/static_pages/radiation.html.erb
<% provide(:subtitle, 'Radiation') %>
<%= render ('layouts/patient_header') %> 
<h2> Radiation </h2>
<ul ng-init="actions = [
    {
      caption: '5000 cGy Radiation treatment',
      desc: 'Operate complete. Repeat skin exambination Q3 months.'
    }
]">
  <div ng-repeat='action in actions'>
      <a href=''><li ng-click='action.show = !action.show'>{{action.caption}}</li></a>
      <p ng-show='action.show'>{{action.desc}}
  </div>
</ul>

app/views/static_pages/scc.html.erb
<% provide(:subtitle, 'Squamous Cell Carcinoma') %>
<%= render ('layouts/patient_header') %> 
<h2> Squamous Cell Carcinoma </h2>

<ul ng-init="actions = [
    {
      caption: 'Obtain Head, Neck and Chest CT',
      desc: 'Operation completed.'
    }]">
  <div ng-repeat='action in actions'>
      <a href=''><li ng-click='action.show = !action.show'>{{action.caption}}</li></a>
      <p ng-show='action.show'>{{action.desc}}
  </div>
</ul>    

<ul ng-init="actions2 = [
    {
      caption: 'Triple Endoscopy: Esophagogastroduodenoscopy, Bronchoscopy, Laryngoscopy',
      desc: '=unused until sanitize problem fixed='
    }]">
  <div ng-repeat='action2 in actions2'>
      <a href=''><li ng-click='action2.show = !action2.show'>{{action2.caption}}</li></a>
      <div ng-show='action2.show'> 
          <p>If mass is primary and &lt;2m, excise with 5mm margins.</p>
          <p>If mass is primary and &gt;2m, excise with 1cm margins, and follow up with <a href='radiation.html'><button>Radiation</button></a></p>
          <p>If mass was a lymph node, find primary, excise primary and Modified Radical Neck Dissection followed by <a href='radiation.html'><button>Radiation</button></a></p>
          <p>if unknown primary, then Modified Radical Neck Dissection followed by <a href='radiation.html'><button>Radiation</button></a></p>
      </div>
  </div>
</ul>    

app/views/static_pages/thyroid.html.erb
<% provide(:subtitle, 'Thyroid') %>
<%= render ('layouts/patient_header') %> 

<h2> Thyroid </h2>

<p> Incomplete page </p>